name = "sheets-api"
main = "src/index.ts"
compatibility_date = "2025-08-16"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787
local_protocol = "http"

[observability.logs]
enabled = true

[vars]
# Global configuration
SA_EMAIL = "service-account@your-project.iam.gserviceaccount.com"
ALLOWED_ORIGINS = "*"

# Projects configuration in JSON format
PROJECTS_CONFIG = '''
{
  "your-project": {
    "sheetId": "YOUR_GOOGLE_SHEET_ID",
    "ranges": {
      "leads": "Leads!A:Z"
    }
  }
}
'''

# Secret should be added via:
# npx wrangler secret put SA_PRIVATE_KEY
